// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduling_service.proto

package ai_flow

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	//_ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScheduleWorkflowRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowName         string            `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Args                 map[string]string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WorkflowJson         string            `protobuf:"bytes,4,opt,name=workflow_json,json=workflowJson,proto3" json:"workflow_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScheduleWorkflowRequest) Reset()         { *m = ScheduleWorkflowRequest{} }
func (m *ScheduleWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleWorkflowRequest) ProtoMessage()    {}
func (*ScheduleWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{0}
}

func (m *ScheduleWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleWorkflowRequest.Unmarshal(m, b)
}
func (m *ScheduleWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleWorkflowRequest.Merge(m, src)
}
func (m *ScheduleWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleWorkflowRequest.Size(m)
}
func (m *ScheduleWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleWorkflowRequest proto.InternalMessageInfo

func (m *ScheduleWorkflowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ScheduleWorkflowRequest) GetWorkflowName() string {
	if m != nil {
		return m.WorkflowName
	}
	return ""
}

func (m *ScheduleWorkflowRequest) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ScheduleWorkflowRequest) GetWorkflowJson() string {
	if m != nil {
		return m.WorkflowJson
	}
	return ""
}

type WorkflowExecutionRequest struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ExecutionId          string            `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkflowName         string            `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Args                 map[string]string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WorkflowExecutionRequest) Reset()         { *m = WorkflowExecutionRequest{} }
func (m *WorkflowExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowExecutionRequest) ProtoMessage()    {}
func (*WorkflowExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{1}
}

func (m *WorkflowExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowExecutionRequest.Unmarshal(m, b)
}
func (m *WorkflowExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowExecutionRequest.Marshal(b, m, deterministic)
}
func (m *WorkflowExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowExecutionRequest.Merge(m, src)
}
func (m *WorkflowExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowExecutionRequest.Size(m)
}
func (m *WorkflowExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowExecutionRequest proto.InternalMessageInfo

func (m *WorkflowExecutionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *WorkflowExecutionRequest) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

func (m *WorkflowExecutionRequest) GetWorkflowName() string {
	if m != nil {
		return m.WorkflowName
	}
	return ""
}

func (m *WorkflowExecutionRequest) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type ScheduleJobRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	JobName              string   `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	ExecutionId          string   `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleJobRequest) Reset()         { *m = ScheduleJobRequest{} }
func (m *ScheduleJobRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleJobRequest) ProtoMessage()    {}
func (*ScheduleJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{2}
}

func (m *ScheduleJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleJobRequest.Unmarshal(m, b)
}
func (m *ScheduleJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleJobRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleJobRequest.Merge(m, src)
}
func (m *ScheduleJobRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleJobRequest.Size(m)
}
func (m *ScheduleJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleJobRequest proto.InternalMessageInfo

func (m *ScheduleJobRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ScheduleJobRequest) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *ScheduleJobRequest) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

type WorkflowInfoResponse struct {
	Result               *ResultProto   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Workflow             *WorkflowProto `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WorkflowInfoResponse) Reset()         { *m = WorkflowInfoResponse{} }
func (m *WorkflowInfoResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowInfoResponse) ProtoMessage()    {}
func (*WorkflowInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{3}
}

func (m *WorkflowInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowInfoResponse.Unmarshal(m, b)
}
func (m *WorkflowInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowInfoResponse.Marshal(b, m, deterministic)
}
func (m *WorkflowInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowInfoResponse.Merge(m, src)
}
func (m *WorkflowInfoResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowInfoResponse.Size(m)
}
func (m *WorkflowInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowInfoResponse proto.InternalMessageInfo

func (m *WorkflowInfoResponse) GetResult() *ResultProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *WorkflowInfoResponse) GetWorkflow() *WorkflowProto {
	if m != nil {
		return m.Workflow
	}
	return nil
}

type ListWorkflowInfoResponse struct {
	Result               *ResultProto     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	WorkflowList         []*WorkflowProto `protobuf:"bytes,2,rep,name=workflow_list,json=workflowList,proto3" json:"workflow_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListWorkflowInfoResponse) Reset()         { *m = ListWorkflowInfoResponse{} }
func (m *ListWorkflowInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowInfoResponse) ProtoMessage()    {}
func (*ListWorkflowInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{4}
}

func (m *ListWorkflowInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowInfoResponse.Unmarshal(m, b)
}
func (m *ListWorkflowInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowInfoResponse.Marshal(b, m, deterministic)
}
func (m *ListWorkflowInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowInfoResponse.Merge(m, src)
}
func (m *ListWorkflowInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowInfoResponse.Size(m)
}
func (m *ListWorkflowInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowInfoResponse proto.InternalMessageInfo

func (m *ListWorkflowInfoResponse) GetResult() *ResultProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListWorkflowInfoResponse) GetWorkflowList() []*WorkflowProto {
	if m != nil {
		return m.WorkflowList
	}
	return nil
}

type WorkflowExecutionResponse struct {
	Result               *ResultProto            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	WorkflowExecution    *WorkflowExecutionProto `protobuf:"bytes,2,opt,name=workflow_execution,json=workflowExecution,proto3" json:"workflow_execution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WorkflowExecutionResponse) Reset()         { *m = WorkflowExecutionResponse{} }
func (m *WorkflowExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowExecutionResponse) ProtoMessage()    {}
func (*WorkflowExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{5}
}

func (m *WorkflowExecutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowExecutionResponse.Unmarshal(m, b)
}
func (m *WorkflowExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowExecutionResponse.Marshal(b, m, deterministic)
}
func (m *WorkflowExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowExecutionResponse.Merge(m, src)
}
func (m *WorkflowExecutionResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowExecutionResponse.Size(m)
}
func (m *WorkflowExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowExecutionResponse proto.InternalMessageInfo

func (m *WorkflowExecutionResponse) GetResult() *ResultProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *WorkflowExecutionResponse) GetWorkflowExecution() *WorkflowExecutionProto {
	if m != nil {
		return m.WorkflowExecution
	}
	return nil
}

type ListWorkflowExecutionResponse struct {
	Result                *ResultProto              `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	WorkflowExecutionList []*WorkflowExecutionProto `protobuf:"bytes,2,rep,name=workflow_execution_list,json=workflowExecutionList,proto3" json:"workflow_execution_list,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *ListWorkflowExecutionResponse) Reset()         { *m = ListWorkflowExecutionResponse{} }
func (m *ListWorkflowExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkflowExecutionResponse) ProtoMessage()    {}
func (*ListWorkflowExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{6}
}

func (m *ListWorkflowExecutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkflowExecutionResponse.Unmarshal(m, b)
}
func (m *ListWorkflowExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkflowExecutionResponse.Marshal(b, m, deterministic)
}
func (m *ListWorkflowExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkflowExecutionResponse.Merge(m, src)
}
func (m *ListWorkflowExecutionResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkflowExecutionResponse.Size(m)
}
func (m *ListWorkflowExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkflowExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkflowExecutionResponse proto.InternalMessageInfo

func (m *ListWorkflowExecutionResponse) GetResult() *ResultProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListWorkflowExecutionResponse) GetWorkflowExecutionList() []*WorkflowExecutionProto {
	if m != nil {
		return m.WorkflowExecutionList
	}
	return nil
}

type JobInfoResponse struct {
	Result               *ResultProto `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Job                  *JobProto    `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *JobInfoResponse) Reset()         { *m = JobInfoResponse{} }
func (m *JobInfoResponse) String() string { return proto.CompactTextString(m) }
func (*JobInfoResponse) ProtoMessage()    {}
func (*JobInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{7}
}

func (m *JobInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfoResponse.Unmarshal(m, b)
}
func (m *JobInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfoResponse.Marshal(b, m, deterministic)
}
func (m *JobInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfoResponse.Merge(m, src)
}
func (m *JobInfoResponse) XXX_Size() int {
	return xxx_messageInfo_JobInfoResponse.Size(m)
}
func (m *JobInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfoResponse proto.InternalMessageInfo

func (m *JobInfoResponse) GetResult() *ResultProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *JobInfoResponse) GetJob() *JobProto {
	if m != nil {
		return m.Job
	}
	return nil
}

type ListJobInfoResponse struct {
	Result               *ResultProto `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	JobList              []*JobProto  `protobuf:"bytes,2,rep,name=job_list,json=jobList,proto3" json:"job_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListJobInfoResponse) Reset()         { *m = ListJobInfoResponse{} }
func (m *ListJobInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobInfoResponse) ProtoMessage()    {}
func (*ListJobInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1e357d293bda59, []int{8}
}

func (m *ListJobInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobInfoResponse.Unmarshal(m, b)
}
func (m *ListJobInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobInfoResponse.Marshal(b, m, deterministic)
}
func (m *ListJobInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobInfoResponse.Merge(m, src)
}
func (m *ListJobInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobInfoResponse.Size(m)
}
func (m *ListJobInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobInfoResponse proto.InternalMessageInfo

func (m *ListJobInfoResponse) GetResult() *ResultProto {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListJobInfoResponse) GetJobList() []*JobProto {
	if m != nil {
		return m.JobList
	}
	return nil
}

func init() {
	proto.RegisterType((*ScheduleWorkflowRequest)(nil), "ai_flow.ScheduleWorkflowRequest")
	proto.RegisterMapType((map[string]string)(nil), "ai_flow.ScheduleWorkflowRequest.ArgsEntry")
	proto.RegisterType((*WorkflowExecutionRequest)(nil), "ai_flow.WorkflowExecutionRequest")
	proto.RegisterMapType((map[string]string)(nil), "ai_flow.WorkflowExecutionRequest.ArgsEntry")
	proto.RegisterType((*ScheduleJobRequest)(nil), "ai_flow.ScheduleJobRequest")
	proto.RegisterType((*WorkflowInfoResponse)(nil), "ai_flow.WorkflowInfoResponse")
	proto.RegisterType((*ListWorkflowInfoResponse)(nil), "ai_flow.ListWorkflowInfoResponse")
	proto.RegisterType((*WorkflowExecutionResponse)(nil), "ai_flow.WorkflowExecutionResponse")
	proto.RegisterType((*ListWorkflowExecutionResponse)(nil), "ai_flow.ListWorkflowExecutionResponse")
	proto.RegisterType((*JobInfoResponse)(nil), "ai_flow.JobInfoResponse")
	proto.RegisterType((*ListJobInfoResponse)(nil), "ai_flow.ListJobInfoResponse")
}

func init() { proto.RegisterFile("scheduling_service.proto", fileDescriptor_3a1e357d293bda59) }

var fileDescriptor_3a1e357d293bda59 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x97, 0x4f, 0x6f, 0x1b, 0x45,
	0x18, 0x87, 0x35, 0x76, 0x48, 0x9c, 0xd7, 0x0d, 0x24, 0x8b, 0xdb, 0xac, 0x5d, 0x97, 0xd8, 0x13,
	0x9a, 0xb6, 0x6e, 0xf0, 0x4a, 0x6e, 0x11, 0x10, 0x24, 0x50, 0x91, 0x7a, 0xa8, 0x85, 0x22, 0xe4,
	0x1c, 0x2a, 0x71, 0xb1, 0x76, 0xed, 0xc9, 0x76, 0x9d, 0xf1, 0xce, 0x76, 0x67, 0x5d, 0xb7, 0x9c,
	0x00, 0x09, 0x29, 0xe2, 0x84, 0x14, 0x71, 0x80, 0x03, 0x12, 0x17, 0xbe, 0x10, 0x77, 0x4e, 0x7c,
	0x0a, 0x4e, 0x68, 0x66, 0xff, 0x78, 0x9d, 0xf5, 0x3a, 0x9b, 0xd8, 0xe9, 0x2d, 0x1e, 0xcf, 0xce,
	0xf3, 0xcc, 0xef, 0x7d, 0x67, 0xd6, 0x01, 0x95, 0xf7, 0x5e, 0x90, 0xfe, 0x88, 0x5a, 0xb6, 0xd9,
	0xe5, 0xc4, 0x7d, 0x65, 0xf5, 0x48, 0xd3, 0x71, 0x99, 0xc7, 0x94, 0x35, 0xdd, 0xea, 0x1e, 0x53,
	0x36, 0xae, 0x6c, 0x0c, 0x09, 0xe7, 0xba, 0x19, 0x8c, 0x57, 0xaa, 0x26, 0x63, 0x26, 0x25, 0x9a,
	0xee, 0x58, 0x9a, 0x6e, 0xdb, 0xcc, 0xd3, 0x3d, 0x8b, 0xd9, 0xdc, 0xff, 0x16, 0xff, 0x87, 0x60,
	0xfb, 0xc8, 0x5f, 0x92, 0x3c, 0x67, 0xee, 0x89, 0x58, 0xa1, 0x43, 0x5e, 0x8e, 0x08, 0xf7, 0x94,
	0x2a, 0xac, 0xdb, 0xfa, 0x90, 0x70, 0x47, 0xef, 0x11, 0x15, 0xd5, 0xd0, 0xfd, 0xf5, 0xce, 0x64,
	0x40, 0xd9, 0x85, 0x8d, 0x71, 0xf0, 0x40, 0x57, 0x8c, 0xaa, 0x39, 0x39, 0xe3, 0x46, 0x38, 0x78,
	0xa8, 0x0f, 0x89, 0xf2, 0x05, 0xac, 0xe8, 0xae, 0xc9, 0xd5, 0x7c, 0x2d, 0x7f, 0xbf, 0xd8, 0x6a,
	0x34, 0x03, 0xc7, 0x66, 0x0a, 0xb2, 0xf9, 0xc4, 0x35, 0xf9, 0x53, 0xdb, 0x73, 0xdf, 0x74, 0xe4,
	0x73, 0x53, 0x90, 0x01, 0x67, 0xb6, 0xba, 0x32, 0x0d, 0x69, 0x73, 0x66, 0x57, 0x3e, 0x81, 0xf5,
	0xe8, 0x39, 0x65, 0x13, 0xf2, 0x27, 0xe4, 0x4d, 0xa0, 0x2b, 0xfe, 0x54, 0x4a, 0xf0, 0xce, 0x2b,
	0x9d, 0x8e, 0x42, 0x41, 0xff, 0xc3, 0x41, 0xee, 0x53, 0x24, 0x36, 0xaf, 0x86, 0x06, 0x4f, 0x5f,
	0x93, 0xde, 0x48, 0x24, 0x93, 0x6d, 0xf7, 0x75, 0xb8, 0x41, 0xc2, 0x27, 0xba, 0x56, 0x3f, 0x58,
	0xbb, 0x18, 0x8d, 0x3d, 0xeb, 0x27, 0x03, 0xca, 0xcf, 0x08, 0xe8, 0xcb, 0x20, 0xa0, 0x15, 0x19,
	0xd0, 0xc3, 0x28, 0xa0, 0x34, 0xad, 0xf3, 0x09, 0x5d, 0x7d, 0xf3, 0x0e, 0x28, 0x61, 0x15, 0xda,
	0xcc, 0xc8, 0xb6, 0xeb, 0x32, 0x14, 0x06, 0xcc, 0x88, 0x97, 0x7b, 0x6d, 0xc0, 0x0c, 0xb9, 0x91,
	0xf3, 0x81, 0xe4, 0x13, 0x81, 0xe0, 0xd7, 0x50, 0x0a, 0xb7, 0xf5, 0xcc, 0x3e, 0x66, 0x1d, 0xc2,
	0x1d, 0x66, 0x73, 0xa2, 0xec, 0xc3, 0xaa, 0x4b, 0xf8, 0x88, 0x7a, 0x12, 0x58, 0x6c, 0x95, 0xa2,
	0x14, 0x3a, 0x72, 0xf8, 0x1b, 0xd1, 0xa9, 0x9d, 0x60, 0x8e, 0xd2, 0x82, 0x42, 0x98, 0xa0, 0x74,
	0x28, 0xb6, 0x6e, 0x25, 0x52, 0xf3, 0x9f, 0x88, 0xe6, 0xe1, 0x9f, 0x10, 0xa8, 0x5f, 0x5b, 0xdc,
	0x5b, 0x02, 0xfe, 0xf3, 0x58, 0x55, 0xa9, 0xc5, 0x3d, 0x35, 0x27, 0x2b, 0x97, 0xe6, 0x10, 0x55,
	0x5b, 0xe0, 0xf1, 0x6f, 0x08, 0xca, 0x33, 0x2a, 0x7b, 0x25, 0x91, 0x43, 0x50, 0x22, 0x91, 0x28,
	0xe5, 0x20, 0x91, 0x9d, 0xf4, 0x3e, 0xf2, 0x17, 0xd9, 0x1a, 0x9f, 0x1f, 0xc7, 0x7f, 0x21, 0xb8,
	0x13, 0xcf, 0x68, 0x51, 0xbf, 0xe7, 0xb0, 0x9d, 0xf4, 0x8b, 0x47, 0x76, 0xa1, 0xe4, 0xcd, 0x84,
	0xa4, 0x0c, 0xb1, 0x0f, 0xef, 0xb5, 0x99, 0xb1, 0x40, 0x09, 0x77, 0x21, 0x3f, 0x60, 0x46, 0x10,
	0xd5, 0x56, 0x34, 0xb5, 0xcd, 0x0c, 0x7f, 0x9e, 0xf8, 0x16, 0xbf, 0x84, 0xf7, 0x05, 0x6d, 0x31,
	0xd2, 0xbe, 0x7f, 0x5e, 0x62, 0x9b, 0x9e, 0x81, 0x13, 0x47, 0x48, 0xa0, 0x5a, 0xff, 0x6c, 0xc2,
	0xd6, 0x51, 0x74, 0xbd, 0x1f, 0xf9, 0xb7, 0xbb, 0xf2, 0x3d, 0x82, 0x77, 0xf9, 0xc8, 0x18, 0x5a,
	0x51, 0x65, 0x94, 0xda, 0x45, 0xf7, 0x68, 0xe5, 0x4e, 0x22, 0xdb, 0xf8, 0x2e, 0xf0, 0x47, 0x3f,
	0xfe, 0xfd, 0xef, 0x59, 0xee, 0x1e, 0xc6, 0x9a, 0x6e, 0x89, 0x2f, 0xb5, 0xc9, 0x5b, 0x45, 0x0b,
	0x43, 0xd7, 0x7c, 0xe8, 0x01, 0x6a, 0x48, 0x85, 0x3e, 0xa1, 0xc4, 0x23, 0x6f, 0x59, 0xc1, 0x87,
	0x0a, 0x85, 0x53, 0x04, 0xdb, 0x8e, 0x3e, 0xe2, 0x11, 0x66, 0x12, 0xd4, 0xe2, 0x2e, 0xfb, 0xd2,
	0x65, 0x0f, 0xd7, 0xe7, 0xb9, 0x48, 0xba, 0x50, 0xf9, 0x19, 0x81, 0x2a, 0xea, 0x3b, 0xbc, 0x16,
	0x97, 0x4c, 0xb9, 0xf8, 0x78, 0x21, 0xf3, 0x1d, 0x14, 0x4d, 0xb2, 0xc4, 0xce, 0x68, 0x48, 0xfc,
	0x87, 0x78, 0x67, 0x1e, 0xde, 0x24, 0xb2, 0x2d, 0x7e, 0x40, 0xb0, 0x41, 0x63, 0x37, 0x06, 0xcf,
	0x80, 0xaf, 0x47, 0x33, 0xd2, 0xee, 0x63, 0xfc, 0x50, 0x2a, 0xdc, 0xc5, 0xb5, 0x79, 0x0a, 0x82,
	0x2b, 0x1c, 0xfe, 0x40, 0x50, 0xe6, 0x9e, 0xee, 0x7a, 0x87, 0x64, 0x9c, 0xb8, 0x46, 0x94, 0xfa,
	0x85, 0xef, 0xd3, 0x0a, 0x9e, 0x37, 0x25, 0x30, 0x3a, 0x90, 0x46, 0x8f, 0xb1, 0x36, 0xc7, 0x68,
	0x72, 0xc7, 0x69, 0xd2, 0xa7, 0x6b, 0x93, 0xb1, 0x10, 0xfc, 0x13, 0x41, 0xf9, 0xc4, 0xa2, 0xf4,
	0x09, 0xa5, 0x09, 0x00, 0xcf, 0x22, 0xb8, 0x37, 0x33, 0xb1, 0xa4, 0xe4, 0x67, 0x52, 0xf2, 0x11,
	0x6e, 0x66, 0x93, 0x14, 0x4e, 0x5d, 0x9d, 0x52, 0xe1, 0xf8, 0x2b, 0x82, 0x9b, 0xe2, 0xf3, 0xb5,
	0x05, 0xf8, 0xb1, 0x74, 0xd3, 0x70, 0x23, 0xbb, 0x9b, 0xf0, 0x3a, 0x43, 0x50, 0x8a, 0x75, 0xf7,
	0xd2, 0xb5, 0x1e, 0x4b, 0xad, 0x26, 0x7e, 0x90, 0x4d, 0x2b, 0x68, 0xfb, 0xdf, 0x11, 0xdc, 0xa2,
	0xb3, 0x4a, 0xb1, 0xd4, 0x72, 0x5e, 0x32, 0xb2, 0xf0, 0x3c, 0x0c, 0xa0, 0x20, 0xdb, 0xaf, 0xcd,
	0x0c, 0xe5, 0x76, 0xe2, 0x34, 0x4e, 0x7e, 0xe8, 0x55, 0xd4, 0xf8, 0x8b, 0x68, 0xea, 0xfc, 0xdd,
	0x93, 0xe4, 0x3a, 0xae, 0xce, 0x20, 0x0f, 0x98, 0xe1, 0xb7, 0xb7, 0x60, 0xbd, 0x80, 0x35, 0xee,
	0x31, 0x67, 0x01, 0xd4, 0x9e, 0x44, 0xd5, 0xf0, 0xed, 0x54, 0x14, 0x73, 0x04, 0xc9, 0x06, 0x70,
	0xc9, 0xa2, 0xfb, 0x7a, 0x20, 0x61, 0xbb, 0xf8, 0x83, 0x14, 0x58, 0x40, 0x10, 0xbc, 0x63, 0x58,
	0x35, 0xc9, 0x22, 0xac, 0xbb, 0x92, 0xb5, 0x83, 0x2b, 0x29, 0xac, 0xa0, 0x95, 0x86, 0x50, 0xa0,
	0xfe, 0x8f, 0x0c, 0x3e, 0x9f, 0x54, 0x9d, 0xea, 0x9a, 0xcb, 0xc6, 0x18, 0x34, 0xc7, 0x57, 0x18,
	0x36, 0x7b, 0x6c, 0xd8, 0xf4, 0x27, 0xf9, 0xff, 0x00, 0x7e, 0x5b, 0xd0, 0x82, 0x95, 0x4f, 0x11,
	0xfa, 0x05, 0x21, 0x63, 0x55, 0x0e, 0x3f, 0xfa, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xf1, 0xc5,
	0x35, 0x69, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulingServiceClient is the client API for SchedulingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulingServiceClient interface {
	// workflow api
	SubmitWorkflow(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error)
	DeleteWorkflow(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error)
	PauseWorkflowScheduling(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error)
	ResumeWorkflowScheduling(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error)
	GetWorkflow(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error)
	ListWorkflows(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*ListWorkflowInfoResponse, error)
	// workflow execution api
	StartNewWorkflowExecution(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecutionResponse, error)
	KillAllWorkflowExecutions(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionResponse, error)
	KillWorkflowExecution(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecutionResponse, error)
	GetWorkflowExecution(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecutionResponse, error)
	ListWorkflowExecutions(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionResponse, error)
	// job api
	StartJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	StopJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	RestartJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	GetJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	ListJobs(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*ListJobInfoResponse, error)
}

type schedulingServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchedulingServiceClient(cc *grpc.ClientConn) SchedulingServiceClient {
	return &schedulingServiceClient{cc}
}

func (c *schedulingServiceClient) SubmitWorkflow(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error) {
	out := new(WorkflowInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/submitWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) DeleteWorkflow(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error) {
	out := new(WorkflowInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/deleteWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) PauseWorkflowScheduling(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error) {
	out := new(WorkflowInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/pauseWorkflowScheduling", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ResumeWorkflowScheduling(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error) {
	out := new(WorkflowInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/resumeWorkflowScheduling", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetWorkflow(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInfoResponse, error) {
	out := new(WorkflowInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/getWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListWorkflows(ctx context.Context, in *ScheduleWorkflowRequest, opts ...grpc.CallOption) (*ListWorkflowInfoResponse, error) {
	out := new(ListWorkflowInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/listWorkflows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) StartNewWorkflowExecution(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecutionResponse, error) {
	out := new(WorkflowExecutionResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/startNewWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) KillAllWorkflowExecutions(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionResponse, error) {
	out := new(ListWorkflowExecutionResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/killAllWorkflowExecutions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) KillWorkflowExecution(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecutionResponse, error) {
	out := new(WorkflowExecutionResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/killWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetWorkflowExecution(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*WorkflowExecutionResponse, error) {
	out := new(WorkflowExecutionResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/getWorkflowExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListWorkflowExecutions(ctx context.Context, in *WorkflowExecutionRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionResponse, error) {
	out := new(ListWorkflowExecutionResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/listWorkflowExecutions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) StartJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/startJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) StopJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/stopJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) RestartJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/restartJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetJob(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/getJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListJobs(ctx context.Context, in *ScheduleJobRequest, opts ...grpc.CallOption) (*ListJobInfoResponse, error) {
	out := new(ListJobInfoResponse)
	err := c.cc.Invoke(ctx, "/ai_flow.SchedulingService/listJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServiceServer is the server API for SchedulingService service.
type SchedulingServiceServer interface {
	// workflow api
	SubmitWorkflow(context.Context, *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error)
	DeleteWorkflow(context.Context, *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error)
	PauseWorkflowScheduling(context.Context, *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error)
	ResumeWorkflowScheduling(context.Context, *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error)
	GetWorkflow(context.Context, *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error)
	ListWorkflows(context.Context, *ScheduleWorkflowRequest) (*ListWorkflowInfoResponse, error)
	// workflow execution api
	StartNewWorkflowExecution(context.Context, *WorkflowExecutionRequest) (*WorkflowExecutionResponse, error)
	KillAllWorkflowExecutions(context.Context, *WorkflowExecutionRequest) (*ListWorkflowExecutionResponse, error)
	KillWorkflowExecution(context.Context, *WorkflowExecutionRequest) (*WorkflowExecutionResponse, error)
	GetWorkflowExecution(context.Context, *WorkflowExecutionRequest) (*WorkflowExecutionResponse, error)
	ListWorkflowExecutions(context.Context, *WorkflowExecutionRequest) (*ListWorkflowExecutionResponse, error)
	// job api
	StartJob(context.Context, *ScheduleJobRequest) (*JobInfoResponse, error)
	StopJob(context.Context, *ScheduleJobRequest) (*JobInfoResponse, error)
	RestartJob(context.Context, *ScheduleJobRequest) (*JobInfoResponse, error)
	GetJob(context.Context, *ScheduleJobRequest) (*JobInfoResponse, error)
	ListJobs(context.Context, *ScheduleJobRequest) (*ListJobInfoResponse, error)
}

// UnimplementedSchedulingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulingServiceServer struct {
}

func (*UnimplementedSchedulingServiceServer) SubmitWorkflow(ctx context.Context, req *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWorkflow not implemented")
}
func (*UnimplementedSchedulingServiceServer) DeleteWorkflow(ctx context.Context, req *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (*UnimplementedSchedulingServiceServer) PauseWorkflowScheduling(ctx context.Context, req *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseWorkflowScheduling not implemented")
}
func (*UnimplementedSchedulingServiceServer) ResumeWorkflowScheduling(ctx context.Context, req *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeWorkflowScheduling not implemented")
}
func (*UnimplementedSchedulingServiceServer) GetWorkflow(ctx context.Context, req *ScheduleWorkflowRequest) (*WorkflowInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (*UnimplementedSchedulingServiceServer) ListWorkflows(ctx context.Context, req *ScheduleWorkflowRequest) (*ListWorkflowInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (*UnimplementedSchedulingServiceServer) StartNewWorkflowExecution(ctx context.Context, req *WorkflowExecutionRequest) (*WorkflowExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartNewWorkflowExecution not implemented")
}
func (*UnimplementedSchedulingServiceServer) KillAllWorkflowExecutions(ctx context.Context, req *WorkflowExecutionRequest) (*ListWorkflowExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillAllWorkflowExecutions not implemented")
}
func (*UnimplementedSchedulingServiceServer) KillWorkflowExecution(ctx context.Context, req *WorkflowExecutionRequest) (*WorkflowExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillWorkflowExecution not implemented")
}
func (*UnimplementedSchedulingServiceServer) GetWorkflowExecution(ctx context.Context, req *WorkflowExecutionRequest) (*WorkflowExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowExecution not implemented")
}
func (*UnimplementedSchedulingServiceServer) ListWorkflowExecutions(ctx context.Context, req *WorkflowExecutionRequest) (*ListWorkflowExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowExecutions not implemented")
}
func (*UnimplementedSchedulingServiceServer) StartJob(ctx context.Context, req *ScheduleJobRequest) (*JobInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (*UnimplementedSchedulingServiceServer) StopJob(ctx context.Context, req *ScheduleJobRequest) (*JobInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJob not implemented")
}
func (*UnimplementedSchedulingServiceServer) RestartJob(ctx context.Context, req *ScheduleJobRequest) (*JobInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartJob not implemented")
}
func (*UnimplementedSchedulingServiceServer) GetJob(ctx context.Context, req *ScheduleJobRequest) (*JobInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (*UnimplementedSchedulingServiceServer) ListJobs(ctx context.Context, req *ScheduleJobRequest) (*ListJobInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}

func RegisterSchedulingServiceServer(s *grpc.Server, srv SchedulingServiceServer) {
	s.RegisterService(&_SchedulingService_serviceDesc, srv)
}

func _SchedulingService_SubmitWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).SubmitWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/SubmitWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).SubmitWorkflow(ctx, req.(*ScheduleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/DeleteWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).DeleteWorkflow(ctx, req.(*ScheduleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_PauseWorkflowScheduling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).PauseWorkflowScheduling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/PauseWorkflowScheduling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).PauseWorkflowScheduling(ctx, req.(*ScheduleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ResumeWorkflowScheduling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ResumeWorkflowScheduling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/ResumeWorkflowScheduling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ResumeWorkflowScheduling(ctx, req.(*ScheduleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/GetWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetWorkflow(ctx, req.(*ScheduleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/ListWorkflows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListWorkflows(ctx, req.(*ScheduleWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_StartNewWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).StartNewWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/StartNewWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).StartNewWorkflowExecution(ctx, req.(*WorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_KillAllWorkflowExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).KillAllWorkflowExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/KillAllWorkflowExecutions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).KillAllWorkflowExecutions(ctx, req.(*WorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_KillWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).KillWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/KillWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).KillWorkflowExecution(ctx, req.(*WorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/GetWorkflowExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetWorkflowExecution(ctx, req.(*WorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListWorkflowExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListWorkflowExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/ListWorkflowExecutions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListWorkflowExecutions(ctx, req.(*WorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/StartJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).StartJob(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/StopJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).StopJob(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_RestartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).RestartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/RestartJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).RestartJob(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetJob(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai_flow.SchedulingService/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListJobs(ctx, req.(*ScheduleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchedulingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ai_flow.SchedulingService",
	HandlerType: (*SchedulingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "submitWorkflow",
			Handler:    _SchedulingService_SubmitWorkflow_Handler,
		},
		{
			MethodName: "deleteWorkflow",
			Handler:    _SchedulingService_DeleteWorkflow_Handler,
		},
		{
			MethodName: "pauseWorkflowScheduling",
			Handler:    _SchedulingService_PauseWorkflowScheduling_Handler,
		},
		{
			MethodName: "resumeWorkflowScheduling",
			Handler:    _SchedulingService_ResumeWorkflowScheduling_Handler,
		},
		{
			MethodName: "getWorkflow",
			Handler:    _SchedulingService_GetWorkflow_Handler,
		},
		{
			MethodName: "listWorkflows",
			Handler:    _SchedulingService_ListWorkflows_Handler,
		},
		{
			MethodName: "startNewWorkflowExecution",
			Handler:    _SchedulingService_StartNewWorkflowExecution_Handler,
		},
		{
			MethodName: "killAllWorkflowExecutions",
			Handler:    _SchedulingService_KillAllWorkflowExecutions_Handler,
		},
		{
			MethodName: "killWorkflowExecution",
			Handler:    _SchedulingService_KillWorkflowExecution_Handler,
		},
		{
			MethodName: "getWorkflowExecution",
			Handler:    _SchedulingService_GetWorkflowExecution_Handler,
		},
		{
			MethodName: "listWorkflowExecutions",
			Handler:    _SchedulingService_ListWorkflowExecutions_Handler,
		},
		{
			MethodName: "startJob",
			Handler:    _SchedulingService_StartJob_Handler,
		},
		{
			MethodName: "stopJob",
			Handler:    _SchedulingService_StopJob_Handler,
		},
		{
			MethodName: "restartJob",
			Handler:    _SchedulingService_RestartJob_Handler,
		},
		{
			MethodName: "getJob",
			Handler:    _SchedulingService_GetJob_Handler,
		},
		{
			MethodName: "listJobs",
			Handler:    _SchedulingService_ListJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduling_service.proto",
}
